#!/bin/sh
# Check if all cloud formation templates are formatted properly

home=$GIT_DIR\\..
#home=".."
templateLoc="templates/"
path=${home}/${templateLoc}

# foreach
for f in `ls $path*.template.yml`; do
    template=`readlink -f ${path}${f}`
    
    # stop if there is a template error
    # discard output if no error
    aws cloudformation validate-template --template-body file://$template > /dev/null || exit 1
done

exit 0
