AWSTemplateFormatVersion: '2010-09-09'
Description: Build a distributed Splunk cluster in a VPC with a bastion host.
Parameters:
  BucketName:
    Description: Name of the S3 bucket storing the CloudFormation template
    Type: String
    MinLength: '1'
    AllowedPattern: "[-_ a-zA-Z0-9]*"
    ConstraintDescription: can contain only alphanumeric characters, spaces, dashes
      and underscores.
  SSHFrom:
    Description: Lockdown SSH access to Bastion host (default can be accessed from
      anywhere)
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
  KeyNameBastion:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the bastion host
    Type: AWS::EC2::KeyPair::KeyName
  KeyNameSplunk:
    Description: Name of an existing EC2 KeyPair to enable SSH access to Splunk SearchHead
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Metadata:
      Comment: VPC with 1 or more subnets across different AZs.
    Properties:
      TemplateURL: 
        Fn::Join:
        - ""
        - - https://s3-eu-west-1.amazonaws.com/
          - Ref: BucketName
          - /splunk-deployment/templates/splunk_network.template.yml
      Parameters:
        SSHLocation:
          Ref: SSHFrom
  BastionHost:
    Type: AWS::CloudFormation::Stack
    Metadata:
      Comment: Bastion host with attached EIP
    Properties:
      TemplateURL: 
        Fn::Join:
        - ""
        - - https://s3-eu-west-1.amazonaws.com/
          - Ref: BucketName
          - /splunk-deployment/templates/splunk_bastion.template.yml
      Parameters:
        SecurityGroupBastion:
          Fn::GetAtt:
          - VPC
          - Outputs.EC2SecurityGroupBastion
        SubnetIdBastion:
          Fn::GetAtt:
          - VPC
          - Outputs.PublicSubnet
        KeyNameBastion:
          Ref: KeyNameBastion
  SearchHeadHost:
    Type: AWS::CloudFormation::Stack
    Metadata:
      Comment: Splunk SearchHead. Web accessible from the internet, and SSH through bastion host.
    Properties:
      TemplateURL: 
        Fn::Join:
        - ""
        - - https://s3-eu-west-1.amazonaws.com/
          - Ref: BucketName
          - /splunk-deployment/templates/splunk_stack.template.yml
      Parameters:
        BucketName:
          Ref: BucketName
        SecurityGroupSearchHead:
          Fn::GetAtt:
          - VPC
          - Outputs.EC2SecurityGroupSearchHead
        SubnetIdSearchHead:
          Fn::GetAtt:
          - VPC
          - Outputs.PublicSubnet
        KeyNameSplunk:
          Ref: KeyNameSplunk
Outputs:
  VpcId:
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.VPCIdent
    Description: VPC ID of newly created VPC
  BastionIpAddress:
    Value:
      Fn::GetAtt:
      - BastionHost
      - Outputs.InstanceIPAddressBastion
    Description: Public IP address of the newly created bastion host
  SearchHeadIpAddress:
    Value:
      Fn::GetAtt:
      - SearchHeadHost
      - Outputs.InstanceIPAddressSearchHead
    Description: Public IP address of the newly created search head host
