AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation tempate for VPC with public and private subnets.
Parameters:
  BucketName:
    Description: Bucket storing the s3 artefacts
    Type: String
    MinLength: '1'
    AllowedPattern: "[-_ a-zA-Z0-9]*"
    ConstraintDescription: can contain only alphanumeric characters, spaces, dashes and underscores.
  SecurityGroupSearchHead:
    Description: Security Group for search head host
    Type: AWS::EC2::SecurityGroup::Id
  SubnetIdSearchHead:
    Description: SubnetId for search head host
    Type: AWS::EC2::Subnet::Id
  KeyNameSplunk:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  SearchHeadHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-1a962263
      KeyName:
        Ref: KeyNameSplunk
      NetworkInterfaces:
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        GroupSet:
          - Ref: SecurityGroupSearchHead
        SubnetId:
          Ref: SubnetIdSearchHead
      IamInstanceProfile:
        !Ref SearchHeadInstanceProfile
      Tags:
      - Key: Name
        Value:
          Ref: AWS::StackName
      - Key: Application
        Value:
          Ref: AWS::StackName
      - Key: Network
        Value: Public
  SearchHeadRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  SearchHeadRolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: searchHead
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:ListBucket
          Resource:
          - Fn::Join:
            - ""
            - "arn:aws:s3:::"
            - Ref: BucketName
        - Effect: Allow
          Action:
          - s3:GetObject
          Resource:
          - Fn::Join:
            - ""
            - "arn:aws:s3:::"
            - Ref: BucketName
            - "/splunk-deployment/*"
      Roles:
      - !Ref SearchHeadRole
  SearchHeadInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref SearchHeadRole
Outputs:
  InstanceIdSearchHead:
    Description: InstanceId of the newly created SearchHead Host
    Value:
      Ref: SearchHeadHost
  InstancePublicIPAddressSearchHead:
    Description: Public IP address of the newly created EC2 Search Head
    Value:
      Fn::GetAtt:
      - SearchHeadHost
      - PublicIp
  InstanceIPAddressSearchHead:
    Description: Private IP address of the newly created EC2 SearchHead Host
    Value:
      Fn::GetAtt:
      - SearchHeadHost
      - PrivateIp
