AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation tempate for VPC with public and private subnets.
Parameters:
  BucketName:
    Description: Bucket storing the s3 artefacts
    Type: String
    MinLength: '1'
    AllowedPattern: "[-_ a-zA-Z0-9]*"
    ConstraintDescription: can contain only alphanumeric characters, spaces, dashes and underscores.
  SecurityGroupBastion:
    Description: Security Group for bastion host
    Type: AWS::EC2::SecurityGroup::Id
  SubnetIdBastion:
    Description: SubnetId for bastion host
    Type: AWS::EC2::Subnet::Id
  KeyNameBastion:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  BastionHost:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            /home/ec2-user/SplunkInternal.pem:
              source: s3://${ BucketName }/splunk-deployment/keys/SplunkInternal.pem
              mode: "000400"
              owner: "ec2-user"
              group: "ec2-user"
    Properties:
      InstanceType: t2.micro
      ImageId: ami-1a962263
      KeyName:
        Ref: KeyNameBastion
      SubnetId:
        Ref: SubnetIdBastion
      SecurityGroupIds:
        - Ref: SecurityGroupBastion
      Tags:
      - Key: Name
        Value: Bastion
  IPAddress:
    Type: AWS::EC2::EIP
  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId:
        Ref: BastionHost
      EIP:
        Ref: IPAddress
Outputs:
  InstanceIdBastion:
    Description: InstanceId of the newly created Bastion Host
    Value:
      Ref: BastionHost
  InstanceIPAddressBastion:
    Description: IP address of the newly created EC2 Bastion Host
    Value:
      Ref: IPAddress
